#!/bin/bash
mvn -version

echo "Configuring Java 8"
if [ ! -d "${OPENSHIFT_DATA_DIR}/jdk" ]; then
  mkdir -p ${OPENSHIFT_DATA_DIR}/jdk
fi

if [ ! -d "${OPENSHIFT_DATA_DIR}/jdk/jdk1.8.0_05" ]; then
  echo "Downloading Java 1.8.0_05"
  pushd ${OPENSHIFT_DATA_DIR}/jdk
  wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
  tar -zxf jdk-8u5-linux-x64.tar.gz
  rm jdk-8u5-linux-x64.tar.gz
fi
echo "Java 8 Configured"
echo "Configuring Maven"
if [ ! -d $OPENSHIFT_DATA_DIR/apache-maven-3.3.3 ]
        then
                echo "Downloading Maven"
                cd $OPENSHIFT_DATA_DIR
                wget http://mirror.cc.columbia.edu/pub/software/apache/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz
                tar xvf *.tar.gz
                rm -f *.tar.gz
fi
echo "Maven Configured - Printing out version"
$OPENSHIFT_DATA_DIR/apache-maven-3.3.3/bin/mvn -version