#!/bin/bash
cd $OPENSHIFT_REPO_DIR
nohup ${OPENSHIFT_DATA_DIR}/jdk/jdk1.8.0_05/bin/java -Xms384m -Xmx412m -jar target/eureka-1.0.0-SNAPSHOT.jar --server.port=${OPENSHIFT_DIY_PORT} --server.address=${OPENSHIFT_DIY_IP} --spring.profiles.active=openshift > $OPENSHIFT_DIY_LOG_DIR/registry.log 2>&1 &
