language: java
jdk:
- oraclejdk8
sudo: false
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: gina.debeukelaer@ordina.be
  password:
    secure: JkCRSo/zIiMZS5ufSNwJ/pLvrzlubHmSl9CRsM3pkBx8qlB3frhabMrCsn0wrjzwI5vU8jZl4DZnDvNJz+WvYKfOokyeBBOserYlLCZA8ogYMZFXBSWMyEeVWyIrA6ztnmuJ2TpbewyshKjKjo+ortmGD6rvQvvXZ2YPkGFBdX0vEd9d+bCCqgbEtXxO/4ikZLc8+1sJZDEYNQFi3R3Rj9Go7RdlrSsBJLQR4jie/K2l0rUKvddJvvTpZJF6+PhAW2RwDzSAz1KbwJ6MnT11pHWblYwkG6dmtpYxOvDTPDQe4b6WNU9S3hBqW94409bihjwG6/JmjrSW7hFGj/4B3xos2qQkptXDe4yBLxvJdC8p2DNfOWb74WcsIBQPPxcOFO9pkIfJbzpm/CSeVz7YOsnROArH0ry+x13TSx9EZN+LA108XGCXdPIi/F7GlUdEUdSpC3EjDlfD3jBT3UWDA7zGpBIfn7B/3Pls8dVCJdXV1mI8NaYIgEFP2ETBUbz8C4mczaxbfBIEqMDmPoRDkuGV0NouG/qS+e7ObMgyT0kRcfm5XBzIU/iA7kEYZP8qI0ARCx7qd1Tb+w7s9hDsnZ2BsmikqtQUrfofwvD45Kdyg/p2adisGGV7Y3Lo1oR50elSMz3oDlJH5EUTmXmysk1okzQtsvUaHBh5hFkpQT8=
  organization: OrdinaBelgiumNV
  space: development
  on:
    repo: Ordineo/eureka
    branch: master
notifications:
  slack:
    secure: FTLz7+bXmKO4r+AMEPtu8IEMGCeiffDgDIIANlw81JxHbIFwYjqHKYP3qCipGQ913N+2Fh34SbFRd6KNX50YEdBlTmdd45lfSC3tG2XxjiM+DY/cz6v//HzqviQqmfUrh5pUbamXcb7TddFkX+yTQ6G69uhXBiwNJMEts2S9CulwoQbX/KhrCtx8yEsnWjlX3xrp2mlPIPxlZzsdYIxzbW5LXFN/55x2M942fTomLbYadCL3c3AjC2wAVG4TA0Jaf646REntmKx0NAjDB8hbCYugrdnewjj6ZHXnHgz8jIgWAQuXR81I00JLj0dFgvA8aghBayJy1ffnRQZiLT+EysctQYQ5hMzkzQ/KG/3KfeAvYB19AEdyv+okVAZoIaOGbv/ThiqvrssNOf3sMJhvWIfD6BUfqE5RGY5Ppnv68mSojUZcELvSjIEOi1OxGkKBaKjg0nFvsqMwM64ky2m9svIA3w4Lecsn9ZjpXRORcXgnsvcN9v7xlfTfVDSjvuu+M/4YeU0cO0qNuEOqSATzOABCSI2UOxbpz1HaNHG7pbqE3vQRwh/dLAuwzEK5wYM0f18dxA1zH4V0gS3TF+OuBxMF0xEKcgpnPF+Ma2a5FzSbg8fmxmIDzSo3SgdrWAjEoSYp3700/U0YswxICEnQMNrq/huYX5LPhODQpva1RwA=
